### ISSUE TITLE
removeChild called twice and rise an exeption

### ISSUE THREAD

**Issue by umbrella-ivan-zhukov** [haradakunihiko/react-confirm#20] opened 2018-07-31 18:05 UTC
dispose() function is called twice and tried to delete already deleted div.

createConfirmation.js:43 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

Video: http://take.ms/yQoLQ

Downgrading from 0.1.17 to 0.1.16 solves the problem http://take.ms/eC2WG.

**Comment by haradakunihiko** [comment] 2018-08-03 05:17
hmm.. I can't reproduce this issue.
Could you share some code to reproduce this or try my react example if it still happens on your environment?
(Note that the dependency for `react-confirm` is locked to 0.1.16 on the example.)

**Comment by umbrella-ivan-zhukov** [comment] 2018-08-03 09:01
@haradakunihiko could you please try to launch the example with 0.1.17 version? I think the issue is 90% there )

**Comment by haradakunihiko** [comment] 2018-08-04 10:57
@umbrella-ivan-zhukov yeah, I did try the react example with 0.1.17 and still can't see the exception.
Did you mean you could reproduce that with the example with 0.1.17 version?

**Comment by krnlde** [comment] 2018-11-05 14:14
I get the same error. The method `dispose` is invoked twice. You can see the screenshots here:
![image](https://user-images.githubusercontent.com/1087002/48002938-4b5cd680-e10d-11e8-8d57-3623ba975f6d.png)
![image](https://user-images.githubusercontent.com/1087002/48003003-79421b00-e10d-11e8-9278-c6681e77d14c.png)

How can I help?

**Comment by mayckcoelho** [comment] 2019-03-01 13:30
@krnlde  I can't say properly if it's related only with bootstrap, or if it's really your case, but I fixed by removing the onClosed function on the creation of my component.

<img width="660" alt="captura de tela 2019-03-01 as 10 29 34" src="https://user-images.githubusercontent.com/18684239/53641186-f76e8400-3c0c-11e9-8f81-5d4ae07082e8.png">

**Comment by LiranBri** [comment] 2020-02-07 11:52
I created a PR for solving it: https://github.com/haradakunihiko/react-confirm/issues/20

**Comment by haradakunihiko** [comment] 2020-02-07 14:36
Thanks! I accept your PR and publish new version to npm.

**Closed** 2021-06-02 02:45 UTC
